apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: provenance-collector
  name: provenance-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provenance-collector
  strategy: {}
  template:
    metadata:
      labels:
        app: provenance-collector
    spec:
      containers:
      - env:
        - name: LOCAL_DEPLOY
          value: "true"
        image: leshl/provenance-collector
        imagePullPolicy: Always
        name: provenance-collector
        resources: {}

    # nodeSelector: 
    #   cwsscheduler: 'true'
status: {}
