apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus-service
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 9099
  # Pod to route service traffic  
  selector:
    app: prometheus-server
