apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
spec:
  type: NodePort
  selector:
    app: postgrest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
