apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
      - name: postgrest
        image: postgrest/postgrest
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/bash","-c","sleep 20 && PGPASSWORD=$POSTGRES_PASSWORD psql $POSTGRES_DB -U $POSTGRES_USER -c \'CREATE SCHEMA IF NOT EXISTS key;\'"]
        env:
        - name: PGRST_DB_URI
          value: "postgres://testUser:testPassword@postgresdb.db.svc.cluster.local:5432/testDB"
        - name: PGRST_DB_SCHEMA
          value: "public"
        - name: PGRST_DB_ANON_ROLE
          value: "testUser"
        # Add other environment variables as needed
