apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  nfs:
    path: /srv/nfs
    server: 192.168.49.1 

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
spec:
  capacity:
    storage: 5Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  nfs:
    path: /srv/nfs
    server: 192.168.49.1

