apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-exp-data
  namespace: cws
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: nfs-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-exp-input
  namespace: cws
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: nfs-pv-2

